### PR TITLE
Fix center state for arrow in collapse fix

### PR DESCRIPTION
**Pull request by shlavik**
Hello!
Looks like CSS attributes were mistakenly applied to another element.
The arrow was especially noticeable off-center at 125% and 175% zoom.

Showcase:
https://user-images.githubusercontent.com/2076748/227840869-03d82806-7957-41f6-934e-9e77be905529.mp4

### CODE REVIEW

**Review by stefashkaa — APPROVED** [review]

**Review by shlavik — COMMENTED** [review]
reasonable fix

**Comment by shlavik** [comment]
wen?

**Comment by shlavik** [comment]
At the moment, when using 125% and 175% zoom in the browser, it can be observed that the chevron is not centered:
image

**Review by stefashkaa — APPROVED** [review]

**Comment by shlavik** [comment]
wen merge?

**Review by Nikita-Polyakov — APPROVED** [review]

**Review by stefashkaa — APPROVED** [review]

**Pull request merged**
